apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-srv-web-01-nginx
  namespace: aisecops
  labels:
    app: srv-web-01
    service: nginx
    managed-by: aisecops-agent
data:
  nginx.conf: |
    # srv-web-01 — nginx
    server {
        listen 80;
        server_name srv-web-01;

        server_tokens on;
        autoindex on;

        root /usr/share/nginx/html;
        index index.html;

        # Block scanning source IP
        deny 172.19.131.174;

        # Rate limit repeated requests
        limit_req_zone $binary_remote_addr zone=perip:10m rate=10r/s;

        location / {
            try_files $uri $uri/ =404;
            limit_req zone=perip burst=20 nodelay;
        }

        # Block common reconnaissance paths
        location ~ ^/\.(git|env|svn) { return 444; }
        location ~ ^/(wp-admin|wp-login|phpmyadmin) { return 444; }
    }
