apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-srv-app-02-sshd
  namespace: aisecops
  labels:
    app: srv-app-02
    service: sshd
    managed-by: aisecops-agent
data:
  sshd_config: |
    # sshd_config — srv-app-02
    # Ubuntu 24.04 LTS | Rôle : serveur applicatif Apache (criticité haute)
    # CMDB : cmdb/srv-app-02.md
    # Accès SSH autorisé depuis : bastion (10.0.0.5) uniquement

    # ─── Réseau ───────────────────────────────────────────────────────────────────
    Port 22
    AddressFamily inet
    ListenAddress 10.0.2.11

    # ─── Authentification ─────────────────────────────────────────────────────────
    LoginGraceTime 60
    PermitRootLogin no
    StrictModes yes
    MaxAuthTries 4
    MaxSessions 5
    MaxStartups 5:50:10

    PubkeyAuthentication yes
    AuthorizedKeysFile .ssh/authorized_keys

    PasswordAuthentication no
    PermitEmptyPasswords no

    KbdInteractiveAuthentication no

    # ─── Restriction des utilisateurs ─────────────────────────────────────────────
    AllowGroups backend-team ops-team

    # ─── PAM / environnement ──────────────────────────────────────────────────────
    UsePAM yes
    AcceptEnv LANG LC_*

    # ─── Fonctionnalités désactivées ──────────────────────────────────────────────
    X11Forwarding no
    PrintMotd no
    AllowAgentForwarding no
    AllowTcpForwarding yes
    GatewayPorts no
    PermitTunnel no

    # ─── Journalisation ───────────────────────────────────────────────────────────
    SyslogFacility AUTHPRIV
    LogLevel VERBOSE

    # ─── SFTP ─────────────────────────────────────────────────────────────────────
    Subsystem sftp /usr/lib/openssh/sftp-server
